### ISSUE TITLE
Create a space in repository for Solr ingest script

### ISSUE THREAD

**Issue by ewlarson** [NYULibraries/spatial_data_repository#20]
Investigate solution for broken data ingest script. 

@andrewbattista Can you point me to that file(s)?

**Comment by andrewbattista** [comment]
Let's table this for now. I should've updated, but it turns out that the script itself is not broken; rather, one of the records we were trying to index was noncompliant. Even so, once we make more progress, I'd like to have you look at our script(s) (both for dev and prod) and make some recommendations on how we can do it more seamlessly, and or augment them for better error messaging, etc if possible. But for now this is not a major action item

**Comment by andrewbattista** [comment]
I'm altering this to the task of creating a place in our repo for the ingest script

**Comment by andrewbattista** [comment]
Closing this one as it's mostly been addressed by the work in #58 - which has now been resolved with a viable script being posted at https://github.com/NYU-DataServices/gis-metadata/blob/master/index-local-collections.rb
