### ISSUE TITLE
Create more elegant 404 error page for application for items not found

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#57]
Right now, we have a fairly crude error page that doesn't diverge too much from the default. We should make it more elegant and in-line with NYU Libraries pages

**Comment by nmwolf** [comment]
Looks like we will have to consider two approaches here: alter the static 404.html page that is currently used (found in public folder) so that it looks more branded, or perform a full rails workflow to create a 404 page like it does any other application page (but produced only when a user enters a URL for a nonexistent page). The advantage to the way it works now is that it puts the lifting (I think) on the server, not the rails application, to recognize and produce the 404 when required. But if we do this using a static file, it may need updating from time to time.

**Comment by nmwolf** [comment]
On pause along with other SDR look and feel enhancements.
